/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "无限的旅途",
  "description": "记录、成长、无限",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/icons/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "wzm"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "无限的旅途，博客，测试"
      }
    ],
    [
      "meta",
      {
        "name": "description",
        "content": "一个半路自学前端的菜鸡建立的个人博客，只为记录收获和踩过的坑"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "name": "robots",
        "content": "all"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "/css/style.css"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/img/icons/site.webmanifest"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/img/icons/apple-touch-icon.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "其他",
      "frontmatter": {
        "title": "其他",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%85%B6%E4%BB%96/",
      "relativePath": "其他/README.md",
      "key": "v-05ba1142",
      "path": "/%E5%85%B6%E4%BB%96/",
      "headers": [
        {
          "level": 2,
          "title": "这里是一些暂时没想好怎么分类的，或者不成体系的文章。",
          "slug": "这里是一些暂时没想好怎么分类的-或者不成体系的文章。"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "wzm的个人博客",
        "bgImage": "/img/show.jpeg",
        "bgImageStyle": {
          "height": "350px"
        },
        "isShowTitleInHome": true,
        "actionText": "About Me",
        "actionLink": "/views/personalInfo/",
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-bc58befe",
      "path": "/"
    },
    {
      "title": "个人博客",
      "frontmatter": {
        "title": "个人博客",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%85%B6%E4%BB%96/%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2/",
      "relativePath": "其他/个人博客/README.md",
      "key": "v-792661a7",
      "path": "/%E5%85%B6%E4%BB%96/%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2/",
      "headers": [
        {
          "level": 2,
          "title": "个人博客是什么",
          "slug": "个人博客是什么"
        }
      ]
    },
    {
      "title": "前端",
      "frontmatter": {
        "title": "前端",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/",
      "relativePath": "前端/README.md",
      "key": "v-0072c96a",
      "path": "/%E5%89%8D%E7%AB%AF/",
      "headers": [
        {
          "level": 2,
          "title": "前端是什么",
          "slug": "前端是什么"
        }
      ]
    },
    {
      "title": "个人博客搭建",
      "frontmatter": {
        "title": "个人博客搭建",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "tags": [
          "vuepress",
          "vuepress-theme-reco"
        ],
        "categories": [
          "blog"
        ],
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%85%B6%E4%BB%96/%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2/%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E7%9A%84%E6%90%AD%E5%BB%BA.html",
      "relativePath": "其他/个人博客/个人博客的搭建.md",
      "key": "v-0a79cf33",
      "path": "/%E5%85%B6%E4%BB%96/%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2/%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E7%9A%84%E6%90%AD%E5%BB%BA.html"
    },
    {
      "title": "Css",
      "frontmatter": {
        "title": "Css",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/%E4%B8%89%E5%A4%A7%E4%BB%B6/css/",
      "relativePath": "前端/三大件/css/README.md",
      "key": "v-0b42283a",
      "path": "/%E5%89%8D%E7%AB%AF/%E4%B8%89%E5%A4%A7%E4%BB%B6/css/",
      "headers": [
        {
          "level": 2,
          "title": "Css是什么",
          "slug": "css是什么"
        }
      ]
    },
    {
      "title": "三大件",
      "frontmatter": {
        "title": "三大件",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/%E4%B8%89%E5%A4%A7%E4%BB%B6/",
      "relativePath": "前端/三大件/README.md",
      "key": "v-cfb29272",
      "path": "/%E5%89%8D%E7%AB%AF/%E4%B8%89%E5%A4%A7%E4%BB%B6/",
      "headers": [
        {
          "level": 2,
          "title": "前端三大件是什么",
          "slug": "前端三大件是什么"
        }
      ]
    },
    {
      "title": "Html",
      "frontmatter": {
        "title": "Html",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/%E4%B8%89%E5%A4%A7%E4%BB%B6/html/",
      "relativePath": "前端/三大件/html/README.md",
      "key": "v-25a05d44",
      "path": "/%E5%89%8D%E7%AB%AF/%E4%B8%89%E5%A4%A7%E4%BB%B6/html/",
      "headers": [
        {
          "level": 2,
          "title": "Html是什么",
          "slug": "html是什么"
        }
      ]
    },
    {
      "title": "Javascript",
      "frontmatter": {
        "title": "Javascript",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/%E4%B8%89%E5%A4%A7%E4%BB%B6/javascript/",
      "relativePath": "前端/三大件/javascript/README.md",
      "key": "v-04776200",
      "path": "/%E5%89%8D%E7%AB%AF/%E4%B8%89%E5%A4%A7%E4%BB%B6/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "Javascript是什么",
          "slug": "javascript是什么"
        }
      ]
    },
    {
      "title": "框架",
      "frontmatter": {
        "title": "框架",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/%E6%A1%86%E6%9E%B6/",
      "relativePath": "前端/框架/README.md",
      "key": "v-3c1ee158",
      "path": "/%E5%89%8D%E7%AB%AF/%E6%A1%86%E6%9E%B6/",
      "headers": [
        {
          "level": 2,
          "title": "框架是什么",
          "slug": "框架是什么"
        }
      ]
    },
    {
      "title": "基础知识",
      "frontmatter": {
        "title": "基础知识",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/",
      "relativePath": "基础知识/README.md",
      "key": "v-1130a8c0",
      "path": "/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/"
    },
    {
      "title": "浏览器工作原理",
      "frontmatter": {
        "title": "浏览器工作原理",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/%E6%B5%8F%E8%A7%88%E5%99%A8%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86/",
      "relativePath": "基础知识/浏览器工作原理/README.md",
      "key": "v-5a985698",
      "path": "/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/%E6%B5%8F%E8%A7%88%E5%99%A8%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86/",
      "headers": [
        {
          "level": 2,
          "title": "浏览器架构概述",
          "slug": "浏览器架构概述"
        },
        {
          "level": 3,
          "title": "什么是浏览器",
          "slug": "什么是浏览器"
        }
      ]
    },
    {
      "title": "Vue",
      "frontmatter": {
        "title": "Vue",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/%E6%A1%86%E6%9E%B6/vue/",
      "relativePath": "前端/框架/vue/README.md",
      "key": "v-6f73afd3",
      "path": "/%E5%89%8D%E7%AB%AF/%E6%A1%86%E6%9E%B6/vue/",
      "headers": [
        {
          "level": 2,
          "title": "Vue是什么",
          "slug": "vue是什么"
        }
      ]
    },
    {
      "title": "动漫",
      "frontmatter": {
        "title": "动漫",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%A8%B1%E4%B9%90/%E5%8A%A8%E6%BC%AB/",
      "relativePath": "娱乐/动漫/README.md",
      "key": "v-53e0dd51",
      "path": "/%E5%A8%B1%E4%B9%90/%E5%8A%A8%E6%BC%AB/",
      "headers": [
        {
          "level": 2,
          "title": "这里是一些动漫的推荐",
          "slug": "这里是一些动漫的推荐"
        }
      ]
    },
    {
      "title": "娱乐",
      "frontmatter": {
        "title": "娱乐",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%A8%B1%E4%B9%90/",
      "relativePath": "娱乐/README.md",
      "key": "v-243ce748",
      "path": "/%E5%A8%B1%E4%B9%90/",
      "headers": [
        {
          "level": 2,
          "title": "这里包括一些个人自制的js小游戏以及一些推荐",
          "slug": "这里包括一些个人自制的js小游戏以及一些推荐"
        }
      ]
    },
    {
      "title": "小说",
      "frontmatter": {
        "title": "小说",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%A8%B1%E4%B9%90/%E5%B0%8F%E8%AF%B4/",
      "relativePath": "娱乐/小说/README.md",
      "key": "v-3cd2179c",
      "path": "/%E5%A8%B1%E4%B9%90/%E5%B0%8F%E8%AF%B4/",
      "headers": [
        {
          "level": 2,
          "title": "这里是一些小说的推荐",
          "slug": "这里是一些小说的推荐"
        }
      ]
    },
    {
      "title": "游戏",
      "frontmatter": {
        "title": "游戏",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%A8%B1%E4%B9%90/%E6%B8%B8%E6%88%8F/",
      "relativePath": "娱乐/游戏/README.md",
      "key": "v-6a85a07c",
      "path": "/%E5%A8%B1%E4%B9%90/%E6%B8%B8%E6%88%8F/",
      "headers": [
        {
          "level": 2,
          "title": "这里是一些游戏的推荐",
          "slug": "这里是一些游戏的推荐"
        }
      ]
    },
    {
      "title": "本站指南",
      "frontmatter": {
        "title": "本站指南",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-6145ba94",
      "path": "/guide/"
    },
    {
      "title": "Git",
      "frontmatter": {
        "title": "Git",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/git/",
      "relativePath": "开发工具/git/README.md",
      "key": "v-65f510ae",
      "path": "/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/git/",
      "headers": [
        {
          "level": 2,
          "title": "Git是什么",
          "slug": "git是什么"
        }
      ]
    },
    {
      "title": "自制js小游戏",
      "frontmatter": {
        "title": "自制js小游戏",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%A8%B1%E4%B9%90/%E6%B8%B8%E6%88%8F/%E8%87%AA%E5%88%B6js%E5%B0%8F%E6%B8%B8%E6%88%8F/",
      "relativePath": "娱乐/游戏/自制js小游戏/README.md",
      "key": "v-75ae3032",
      "path": "/%E5%A8%B1%E4%B9%90/%E6%B8%B8%E6%88%8F/%E8%87%AA%E5%88%B6js%E5%B0%8F%E6%B8%B8%E6%88%8F/",
      "headers": [
        {
          "level": 2,
          "title": "这里是一些我的自制js小游戏",
          "slug": "这里是一些我的自制js小游戏"
        }
      ]
    },
    {
      "title": "网络游戏",
      "frontmatter": {
        "title": "网络游戏",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%A8%B1%E4%B9%90/%E6%B8%B8%E6%88%8F/%E7%BD%91%E7%BB%9C%E6%B8%B8%E6%88%8F/",
      "relativePath": "娱乐/游戏/网络游戏/README.md",
      "key": "v-3b12dc13",
      "path": "/%E5%A8%B1%E4%B9%90/%E6%B8%B8%E6%88%8F/%E7%BD%91%E7%BB%9C%E6%B8%B8%E6%88%8F/",
      "headers": [
        {
          "level": 2,
          "title": "这里是一些网络游戏的推荐",
          "slug": "这里是一些网络游戏的推荐"
        }
      ]
    },
    {
      "title": "开发工具",
      "frontmatter": {
        "title": "开发工具",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/",
      "relativePath": "开发工具/README.md",
      "key": "v-30bb3e9b",
      "path": "/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/"
    },
    {
      "title": "Github",
      "frontmatter": {
        "title": "Github",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/github/",
      "relativePath": "开发工具/github/README.md",
      "key": "v-9cb14cac",
      "path": "/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/github/",
      "headers": [
        {
          "level": 2,
          "title": "Github是什么",
          "slug": "github是什么"
        }
      ]
    },
    {
      "title": "Vscode",
      "frontmatter": {
        "title": "Vscode",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/vscode/README%20copy%202.html",
      "relativePath": "开发工具/vscode/README copy 2.md",
      "key": "v-50594f83",
      "path": "/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/vscode/README%20copy%202.html",
      "headers": [
        {
          "level": 2,
          "title": "Vscode是什么",
          "slug": "vscode是什么"
        }
      ]
    },
    {
      "title": "数组",
      "frontmatter": {
        "title": "数组",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E7%AE%97%E6%B3%95/%E5%88%B7%E9%A2%98/%E6%95%B0%E7%BB%84/",
      "relativePath": "算法/刷题/数组/README.md",
      "key": "v-1f9a5ad7",
      "path": "/%E7%AE%97%E6%B3%95/%E5%88%B7%E9%A2%98/%E6%95%B0%E7%BB%84/",
      "headers": [
        {
          "level": 2,
          "title": "数组是什么",
          "slug": "数组是什么"
        }
      ]
    },
    {
      "title": "Leetcode",
      "frontmatter": {
        "title": "Leetcode",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E7%AE%97%E6%B3%95/%E5%88%B7%E9%A2%98/",
      "relativePath": "算法/刷题/README.md",
      "key": "v-4871c61e",
      "path": "/%E7%AE%97%E6%B3%95/%E5%88%B7%E9%A2%98/",
      "headers": [
        {
          "level": 2,
          "title": "Leetcode是什么",
          "slug": "leetcode是什么"
        }
      ]
    },
    {
      "title": "算法",
      "frontmatter": {
        "title": "算法",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E7%AE%97%E6%B3%95/",
      "relativePath": "算法/README.md",
      "key": "v-a23ee6dc",
      "path": "/%E7%AE%97%E6%B3%95/",
      "headers": [
        {
          "level": 2,
          "title": "算法是什么",
          "slug": "算法是什么"
        }
      ]
    },
    {
      "title": "数据结构",
      "frontmatter": {
        "title": "数据结构",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E7%AE%97%E6%B3%95/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/",
      "relativePath": "算法/数据结构/README.md",
      "key": "v-9f5bf676",
      "path": "/%E7%AE%97%E6%B3%95/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/",
      "headers": [
        {
          "level": 2,
          "title": "数据结构是什么",
          "slug": "数据结构是什么"
        }
      ]
    },
    {
      "title": "排序",
      "frontmatter": {
        "title": "排序",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E7%AE%97%E6%B3%95/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/%E6%8E%92%E5%BA%8F/",
      "relativePath": "算法/数据结构/排序/README.md",
      "key": "v-779ccece",
      "path": "/%E7%AE%97%E6%B3%95/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/%E6%8E%92%E5%BA%8F/",
      "headers": [
        {
          "level": 2,
          "title": "排序是什么",
          "slug": "排序是什么"
        }
      ]
    },
    {
      "title": "联系我",
      "frontmatter": {
        "title": "联系我",
        "date": "2022-06-06T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E8%81%94%E7%B3%BB%E6%88%91/",
      "relativePath": "联系我/README.md",
      "key": "v-41b68480",
      "path": "/%E8%81%94%E7%B3%BB%E6%88%91/",
      "headers": [
        {
          "level": 2,
          "title": "QQ",
          "slug": "qq"
        }
      ]
    },
    {
      "title": "iconfont引入和使用",
      "frontmatter": {
        "title": "iconfont引入和使用",
        "date": "2022-10-09T00:00:00.000Z",
        "isTimeLine": false,
        "isShowComment": false,
        "readingShow": "top"
      },
      "regularPath": "/%E5%85%B6%E4%BB%96/iconfont%E5%BC%95%E5%85%A5%E5%92%8C%E4%BD%BF%E7%94%A8.html",
      "relativePath": "其他/iconfont引入和使用.md",
      "key": "v-28721022",
      "path": "/%E5%85%B6%E4%BB%96/iconfont%E5%BC%95%E5%85%A5%E5%92%8C%E4%BD%BF%E7%94%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "Web 端使用",
          "slug": "web-端使用"
        },
        {
          "level": 3,
          "title": "icon 单个使用",
          "slug": "icon-单个使用"
        },
        {
          "level": 3,
          "title": "Unicode方法使用",
          "slug": "unicode方法使用"
        },
        {
          "level": 3,
          "title": "类名方法使用",
          "slug": "类名方法使用"
        },
        {
          "level": 3,
          "title": "伪元素方法使用",
          "slug": "伪元素方法使用"
        },
        {
          "level": 3,
          "title": "symbol 方法使用",
          "slug": "symbol-方法使用"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vuepress Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/vuepress/",
      "key": "v-dfb71430",
      "path": "/tag/vuepress/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vuepress-theme-reco Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/vuepress-theme-reco/",
      "key": "v-6cf72f86",
      "path": "/tag/vuepress-theme-reco/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "blog Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/blog/",
      "key": "v-628eda6f",
      "path": "/categories/blog/"
    }
  ],
  "themeConfig": {
    "logo": "/img/logo.png",
    "type": "blog",
    "smoothScroll": true,
    "blogConfig": {
      "category": {
        "location": 1,
        "text": "分类"
      },
      "tag": {
        "location": 2,
        "text": "标签"
      }
    },
    "authorAvatar": "/img/avatar.png",
    "lastUpdated": "上次更新时间",
    "author": "wzm",
    "startYear": "2022",
    "nav": [
      {
        "text": "本站指南",
        "link": "/guide/",
        "icon": "reco-eye"
      },
      {
        "text": "基础知识",
        "link": "/基础知识/",
        "icon": "reco-sticky",
        "items": [
          {
            "text": "浏览器工作原理",
            "link": "/基础知识/浏览器工作原理"
          }
        ]
      },
      {
        "text": "前端",
        "link": "/前端/",
        "icon": "reco-document",
        "items": [
          {
            "text": "三大件",
            "link": "/前端/三大件/",
            "items": [
              {
                "text": "Html",
                "link": "/前端/三大件/html"
              },
              {
                "text": "Css",
                "link": "/前端/三大件/css"
              },
              {
                "text": "Javascript",
                "link": "/前端/三大件/javascript"
              }
            ]
          },
          {
            "text": "框架",
            "link": "/前端/框架/",
            "items": [
              {
                "text": "Vue",
                "link": "/前端/框架/Vue"
              }
            ]
          }
        ]
      },
      {
        "text": "算法",
        "icon": "reco-npm",
        "link": "/算法/",
        "items": [
          {
            "text": "数据结构",
            "link": "/算法/数据结构/",
            "items": [
              {
                "text": "排序",
                "link": "/算法/数据结构/排序"
              }
            ]
          },
          {
            "text": "刷题",
            "link": "/算法/刷题/",
            "items": [
              {
                "text": "刷题指南（点我）",
                "link": "https://programmercarl.com/"
              },
              {
                "text": "数组",
                "link": "/算法/刷题/数组"
              }
            ]
          }
        ]
      },
      {
        "text": "开发工具",
        "icon": "reco-coding",
        "items": [
          {
            "text": "Git",
            "link": "/开发工具/git"
          },
          {
            "text": "Github",
            "link": "/开发工具/github"
          },
          {
            "text": "Vscode",
            "link": "/开发工具/vscode"
          }
        ]
      },
      {
        "text": "其他",
        "icon": "reco-other",
        "link": "/其他/",
        "items": [
          {
            "text": "个人博客",
            "link": "/其他/个人博客/"
          }
        ]
      },
      {
        "text": "娱乐",
        "icon": "reco-color",
        "link": "/娱乐/",
        "items": [
          {
            "text": "游戏",
            "link": "娱乐/游戏/",
            "items": [
              {
                "text": "自制js小游戏",
                "link": "娱乐/游戏/自制js小游戏"
              },
              {
                "text": "网络游戏",
                "link": "娱乐/游戏/网络游戏"
              }
            ]
          },
          {
            "text": "小说",
            "link": "娱乐/小说/"
          },
          {
            "text": "动漫",
            "link": "娱乐/动漫/"
          }
        ]
      },
      {
        "text": "联系我",
        "icon": "reco-account",
        "items": [
          {
            "text": "QQ",
            "link": "/联系我/"
          },
          {
            "text": "仓库",
            "items": [
              {
                "text": "Github",
                "link": "https://github.com/wzm-htdz/"
              },
              {
                "text": "Gitee",
                "link": "https://gitee.com/wzm-htdz/"
              }
            ]
          }
        ]
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ],
    "subSidebar": "auto",
    "search": true,
    "searchMaxSuggestions": 10,
    "vssueConfig": {
      "platform": "github-v4",
      "owner": "wzm-htdz",
      "repo": "myblog",
      "clientId": "c3541062f9a7e2a8d7fd",
      "clientSecret": "26915d150dff588418a9a8661623ef88df821c76"
    }
  }
}