/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "vuepress": {
      "key": "vuepress",
      "scope": "tags",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-0a79cf33"
      ]
    },
    "vuepress-theme-reco": {
      "key": "vuepress-theme-reco",
      "scope": "tags",
      "path": "/tag/vuepress-theme-reco/",
      "pageKeys": [
        "v-0a79cf33"
      ]
    }
  },
  "categories": {
    "blog": {
      "key": "blog",
      "scope": "categories",
      "path": "/categories/blog/",
      "pageKeys": [
        "v-0a79cf33"
      ]
    }
  },
  "timeline": {}
}