/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "vuepress",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/vuepress/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "vuepress-theme-reco",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/vuepress-theme-reco/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "blog",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/blog/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]